### ISSUE TITLE
Support Non-Correlated Subqueries in Joins

### ISSUE THREAD

**Issue by geofflane** [elixir-lang/ecto#1010]
The current support for joining to a fragment is limited and generates SQL that does something like
```INNER JOIN (SELECT * FROM Foo WHERE something = outer.something) AS f1 ON TRUE```
That limits the sub-selected to correlated subqueries where you can reference the join condition in the WHERE clause of the subquery to something in the outer query scope. This _might_ always be possible, but it's not the only way to write a synthetic join.

I expected to be able to generate a query like:
```INNER JOIN (SELECT * FROM Foo) AS f1 ON f1.something = outer.something```

The failing test (in Postgres) for that is something like the following:
```
  test "join with fragment subquery" do
    query = Model
            |> join(:inner, [p], q in fragment("SELECT * FROM model2 AS m2 WHERE m2.field = ?", ^10), p.id == q.id)
            |> select([p], {p.id, ^0})
            |> where([p], p.id > 0 and p.id < ^100)
            |> normalize
    assert SQL.all(query) ==
           ~s{SELECT m0."id", $1 FROM "model" AS m0 INNER JOIN } <>
           ~s{(SELECT * FROM model2 AS m2 WHERE m2.id = m0."x" AND m2.field = $2) AS f1 ON m0."id" = f1."id" } <>
           ~s{WHERE ((m0."id" > 0) AND (m0."id" < $3))}
  end
```

**Comment by geofflane** [comment]
The actual query I was trying to write, where I ran into this problem was the following:
```
from st in query,
    join: a in assoc(st, :agency),
    join: t in assoc(st, :trip),
    join: es in fragment("SELECT * FROM effective_services(?, ?)", ^start_time, ^end_time), on: t.service_id == es.service_id,
    where: fragment("(start_time(?) + ?) BETWEEN (? AT TIME ZONE ?) AND (? AT TIME ZONE ?)", es.date, st.departure_time, ^start_time, a.timezone, ^end_time, a.timezone),
    order_by: fragment("start_time(?) + ?", es.date, st.departure_time),
    select: [st.id, st.stop_sequence, st.stop_headsign, st.pickup_type, st.drop_off_type, st.shape_dist_traveled, st.agency_id, st.stop_id, st.trip_id,
          fragment("to_char(((start_time(?) + ?) AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS') as arrival_time", es.date, st.arrival_time),
          fragment("to_char(((start_time(?) + ?) AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS') as departure_time", es.date, st.departure_time)]
```

The sub-query join, in this case, was a call to a function that returns a table. That doesn't seem to work even in the correlated case:

```
    from st in query,
    join: a in assoc(st, :agency),
    join: t in assoc(st, :trip),
    join: es in fragment("SELECT * FROM effective_services(?, ?) AS es WHERE es.service_id = ?", ^start_time, ^end_time, t.service_id),
    where: fragment("(start_time(?) + ?) BETWEEN (? AT TIME ZONE ?) AND (? AT TIME ZONE ?)", es.date, st.departure_time, ^start_time, a.timezone, ^end_time, a.timezone),
    order_by: fragment("start_time(?) + ?", es.date, st.departure_time),
    select: [st.id, st.stop_sequence, st.stop_headsign, st.pickup_type, st.drop_off_type, st.shape_dist_traveled, st.agency_id, st.stop_id, st.trip_id,
          fragment("to_char(((start_time(?) + ?) AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS') as arrival_time", es.date, st.arrival_time),
          fragment("to_char(((start_time(?) + ?) AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS') as departure_time", es.date, st.departure_time)]
```

**Comment by parkerl** [comment]
I can confirm having the same issue. Here is a query that behaves the same:

```
    Repo.all(
      FishLanded
      |> join(:inner, [f], p in fragment("SELECT * FROM fish_landed fl "), f.id == p.id)
    ) 
```

```
** (MatchError) no match of right hand side value: {:fragment, [], [raw: "SELECT * FROM fish_landed fl "]}
    (elixir) lib/macro.ex:194: anonymous fn/3 in Macro.do_prewalk/3
    (elixir) lib/enum.ex:1102: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1102: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:193: Macro.do_prewalk/3
```

**Comment by parkerl** [comment]
Erlang 18
Elixir 1.1.1
Ecto master
Postgrex 0.9.1
Postgres 9.4

My bad for not posting above.

**Comment by josevalim** [comment]
Perfect, thank you for the report!

**Comment by parkerl** [comment]
@josevalim @bcardarella PR #1123 fixes my example above. :tada: 

@geofflane Can you try your example as well?

**Comment by bcardarella** [comment]
:heart: :heartbeat: :heart: :heartbeat:

**Comment by josevalim** [comment]
Oh, beautiful. Closing this too!

**Comment by geofflane** [comment]
:+1: I was able to get my example working as well

**Comment by madshargreave** [comment]
@geofflane Were you able to perform a join on the result of the function, if so, mind sharing how you managed to do it? I keep getting syntax errors related to parentheses

**Comment by geofflane** [comment]
@madshargreave Something like:

```
 from st in query,
 join: a in assoc(st, :agency),
 join: t in assoc(st, :trip),
 join: es in fragment("SELECT * FROM effective_services(?, ?)", ^start_date, ^end_date), on: es.service_id == t.service_id,
```

**Comment by madshargreave** [comment]
Perfect, thanks!
