### ISSUE TITLE
Using multiple ecto repos causes timeout on unique_index

### ISSUE THREAD

**Issue by Gazler** [elixir-lang/ecto#1015]
I have created a sample repository to show this issue at https://github.com/Gazler/ecto_index_timeout

The gist of the issue is that if I create a migration with a unique index:

```elixir
defmodule FirstApp.Repo.Migrations.CreateUsers do
  use Ecto.Migration

  def change do
    create table(:users) do
      add :name, :string
    end

    create unique_index(:users, [:name])
  end
end
```

And a model:

```elixir
defmodule FirstApp.User do
  use Ecto.Model

  schema "users" do
    field :name, :string
  end
end
```

Then use the same model in an umbrella application with a different repo in the tests:

```elixir
defmodule FirstAppTest do
  use ExUnit.Case

  test "creating a user" do
    FirstApp.Repo.insert!(%FirstApp.User{name: "foo"})
  end
end
```

```elixir
defmodule SecondAppTest do
  use ExUnit.Case

  test "creating a user" do
    SecondApp.Repo.insert!(%FirstApp.User{name: "foo"})
  end
end
```

This causes a timeout. Interestingly, if the same Repo is used in both instances then an `Ecto.ConstraintError` is raised.

**Comment by Gazler** [comment]
Actually - on after another test - it seems like the umbrella part is irrelevant. Having the unique index and two repos causes the same issue. I'll make another github repo to demonstrate this.

**Comment by Gazler** [comment]
Here's another version that has the same problem but doesn't use an umbrea:

https://github.com/Gazler/ecto_index_timeout/tree/one_app

**Comment by Tica2** [comment]
To run tests in consistent way, pool Repo use one connection and 
transaction is started: (** BEGIN [] OK** )
Ecto.Adapters.SQL.begin_test_transaction(FirstApp.Repo)

After tests in first_app this connection stil have active transaction.

In second app we have DB deadlock because is inserted same "foo" on uniqe index.

add on_exit in first test:
```elixir
setup do
    on_exit fn ->
      Ecto.Adapters.SQL.rollback_test_transaction(FirstApp.Repo)
    end
    :ok
end
```
and tests works fine

First output:

```bash
petrica@mac ~/tmp/elixir-ecto/ecto_index_timeout > mix test
==> first_app

09:12:27.914 [debug] BEGIN [] OK query=0.3ms

09:12:27.915 [debug] SAVEPOINT ecto_sandbox [] OK query=0.3ms

09:12:27.962 [debug] INSERT INTO "users" ("name") VALUES ($1) RETURNING "id" ["foo"] OK query=0.9ms
.

Finished in 0.1 seconds (0.1s on load, 0.01s on tests)
1 test, 0 failures

Randomized with seed 949991
==> second_app

09:12:28.022 [debug] BEGIN [] OK query=0.2ms

09:12:28.023 [debug] SAVEPOINT ecto_sandbox [] OK query=0.4ms


  1) test creating a user (SecondAppTest)
     test/second_app_test.exs:4
     ** (exit) exited in: GenServer.call(#PID<0.194.0>, {:query, "INSERT INTO \"users\" (\"name\") VALUES ($1) RETURNING \"id\"", ["foo"]}, 5000)
         ** (EXIT) time out
     stacktrace:
       (elixir) lib/gen_server.ex:539: GenServer.call/3
       (postgrex) lib/postgrex/connection.ex:102: Postgrex.Connection.query/4
       (ecto) lib/ecto/adapters/postgres/connection.ex:31: Ecto.Adapters.Postgres.Connection.query/4
       (stdlib) timer.erl:197: :timer.tc/3
       (ecto) lib/ecto/adapters/sql.ex:246: Ecto.Adapters.SQL.query/7
       (ecto) lib/ecto/pool.ex:159: Ecto.Pool.do_run/4
       (ecto) lib/ecto/adapters/sql.ex:231: Ecto.Adapters.SQL.query/6
       (ecto) lib/ecto/adapters/sql.ex:209: Ecto.Adapters.SQL.query/5



Finished in 5.0 seconds
1 test, 1 failure

Randomized with seed 42019
```

**Comment by Gazler** [comment]
@Tica2 Thanks for the advice, this fixes the issue.

I was also informed that it is better to use a single shared repo to take advantage of query caching.
