### ISSUE TITLE
Error on executing ecto.migrate from Mix.Task.run

### ISSUE THREAD

**Issue by slashmili** [elixir-lang/ecto#1029]
Hi there,

I just got the new version of phoenix(1.0.3) and Ecto 1.0.5  and postgrex 0.9.1 was installed for me. The problem is `mix test` fails on phoenix. After debugging the issue I found out that `ecto.migrate` can not get triggered by  `Mix.Task.run`

```
bash-3.2$ MIX_ENV=test iex -S mix
Erlang/OTP 18 [erts-7.0.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.0.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Mix.Task.run "ecto.migrate", ["--quiet"]
** (ArgumentError) argument error
           :erlang.exit(nil, :normal)
    (ecto) lib/ecto/adapters/postgres.ex:55: Ecto.Adapters.Postgres.stop/2
    (ecto) lib/mix/ecto.ex:75: Mix.Ecto.ensure_stopped/2
```

**Comment by josevalim** [comment]
Good catch, fixed in master and v1.0. Thank you!
