### ISSUE TITLE
Ecto.migrate fails on maps using postgres

### ISSUE THREAD

**Issue by nathanjohnson320** [elixir-lang/ecto#1078]
When I run the sample migration from the docs:
```
create table(:users) do
  add :data, :map
end
```

I get the following error:
```
23:33:18.757 [info]  create table users
** (Postgrex.Error) ERROR (undefined_object): type "jsonb" does not exist
    (ecto) lib/ecto/adapters/sql.ex:185: Ecto.Adapters.SQL.query!/5
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:55: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:74: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:72: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
    (ecto) lib/ecto/migration/runner.ex:23: Ecto.Migration.Runner.run/6
```

**Comment by sorentwo** [comment]
Make sure you are using Postgres 9.4. There isn't support for jsonb in 9.3 or below.

**Comment by nathanjohnson320** [comment]
yep that was the issue. Thanks for the help!
