### ISSUE TITLE
Data.preload error on has_one with UUID

### ISSUE THREAD

**Issue by divmgl** [elixir-lang/ecto#1120]
Getting a weird error and I'm not sure how to proceed. I have a schema `Account` that has one-to-many relationship with another `Tenant` through UUIDs. When I try to preload, I get the following error:

```
** (Ecto.CastError) deps/ecto/lib/ecto/association.ex:336: cannot dump cast value `[<<154, 42, 210, 62, 151, 130, 76, 179, 141, 70, 143, 43, 229, 3, 195, 48>>]` to type {:array, :binary_id} in query:

from t in Topaz.Schema.Tenant,
  where: t.id in ^[<<154, 42, 210, 62, 151, 130, 76, 179, 141, 70, 143, 43, 229, 3, 195, 48>>]

Error when casting value to `Topaz.Schema.Tenant.id`
        (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1102: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
```

`Tenant.id` is a binary value, as is `Account.tenant_id`. Here's the schemas for each of these.

```elixir
defmodule Topaz.Schema do
  defmacro __using__(_) do
    quote do
      use Ecto.Model

      @primary_key {:id, :binary_id, autogenerate: true}
      @foreign_key_type :binary_id
    end
  end
end
```
```elixir
defmodule Topaz.Schema.Account do
  use Topaz.Schema # Loading primary key through here
  alias Topaz.Data
  alias Topaz.Schema.Tenant

  schema "account" do
    ### Arbitrary fields here, including id and username ###
    field :tenant_id, :binary
    has_one :tenant, Topaz.Schema.Tenant, foreign_key: :id, references: :tenant_id
  end
end
```
```elixir
defmodule Topaz.Schema.Tenant do
  use Topaz.Schema
  alias Topaz.Schema.Tenant
  alias Topaz.Data

  schema "tenant" do
    field :name, :string
    field :active, :boolean
    field :sole_proprietor, :boolean
    field :created_on, Ecto.DateTime
  end
end
```

Not sure what's going on. Should be something simple, but it doesn't seem to be working at all.

**Comment by divmgl** [comment]
Syntactical error, the solution was to simplify the schema:

```
schema "account" do
    field :username, :string
    field :password, :binary
    field :name, :string
    field :created_on, Ecto.DateTime
    field :active, :boolean    
    belongs_to :tenant, Tenant
  end
```
```
schema "tenant" do
    field :name, :string
    field :active, :boolean
    field :sole_proprietor, :boolean
    field :created_on, Ecto.DateTime
  end
```
