### ISSUE TITLE
Random issue when running mix test

### ISSUE THREAD

**Issue by stevedomin** [elixir-lang/ecto#1263]
I have had that error a couple of times now when running `mix test` with the Ecto 2.0 beta.

I'm not sure where it's coming from but thought it would be useful to report it.

```elixir
# run test once with incorrect test
$ mix test test/controllers/session_controller_test.exs
....

Finished in 0.4 seconds (0.2s on load, 0.2s on tests)
4 tests, 0 failures

Randomized with seed 243590

# change file to fix, test should now fail but instead I get this error
$ mix test test/controllers/session_controller_test.exs
** (exit) exited in: GenServer.call(Repo.Pool, {:mode, :manual}, 5000)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:564: GenServer.call/3
    (elixir) lib/code.ex:363: Code.require_file/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/tasks/test.ex:186: Mix.Tasks.Test.run/1

00:22:12.487 [error] GenServer #PID<0.375.0> terminating
** (stop) exited in: GenServer.call(Repo.Pool, {:mode, :manual}, 5000)
    ** (EXIT) no process

# run mix test again, working fine now (failing test is expected)
$ mix test test/controllers/session_controller_test.exs
..

  1) test POST /auth/callback/identity with incorrect details (SessionControllerTest)
     test/controllers/session_controller_test.exs:26
     ** (FunctionClauseError) no function clause matching in Kernel.=~/2
     stacktrace:
       (elixir) lib/kernel.ex:1500: Kernel.=~(nil, "Signed in as")
       test/controllers/session_controller_test.exs:33

.

Finished in 0.4 seconds (0.2s on load, 0.2s on tests)
4 tests, 1 failure
```

Let me know if you need more details.

**Comment by josevalim** [comment]
I know exactly what this is. I will fix this and a couple bugs and ship a new beta.

**Comment by josevalim** [comment]
Related to #1259.

**Comment by josevalim** [comment]
@stevedomin please try the following solution. Remove the two `Mix.Task.run` calls from your test_helper.exs and add the following to your `mix.exs` inside the `defp aliases` function:

    "test": ["ecto.create -r Demo.Repo --quiet", "ecto.migrate -r Demo.Repo", "test"]

This should be enough to make everything work as expected. You may need Ecto master.

**Comment by stevedomin** [comment]
Thanks @josevalim
