### ISSUE TITLE
Aggregate function with order_by

### ISSUE THREAD

**Issue by singachea** [elixir-lang/ecto#1302]
When I try chaining query for this aggregate function with `order_by`,  I get the following problem:

```bash
iex(18)> query = Author |> order_by(:id)
#Ecto.Query<from a in Myapp.Author, order_by: [asc: a.id]>
iex(19)> Myapp.Repo.one from a in query, select: count("*")
warning: Myapp.Repo.one/2 is deprecated, please use all/2, aggregate/3 or first/2 accordingly
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:215: :elixir.erl_eval/3
    (elixir) src/elixir.erl:203: :elixir.eval_forms/4
    (iex) lib/iex/evaluator.ex:135: IEx.Evaluator.handle_eval/6

[debug] SELECT count('*') FROM "authors" AS a0 ORDER BY a0."id" [] ERROR query=1.2ms
** (Postgrex.Error) ERROR (grouping_error): column "a0.id" must appear in the GROUP BY clause or be used in an aggregate function
    (ecto) lib/ecto/adapters/sql.ex:367: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:122: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/4
    (ecto) lib/ecto/repo/queryable.ex:59: Ecto.Repo.Queryable.one/4
```

First, I thought this is postgresql's problem, but it seems Ecto doesn't generate the desirable query. The chaining query should generate the following sql query:

```sql
SELECT count('*') FROM (SELECT * FROM "authors" AS a0 ORDER BY a0."id") AS a1;
```

The `Myapp.Repo.first` would give same problem since it tries to sort, I guess:

```elixir
Myapp.Repo.first from a in Author, select: count("*")
```

**Comment by josevalim** [comment]
@singachea Please use `Repo.aggregate`. That's the only function that will change your query to build aggregations. The others assume you are building a correct query.

**Comment by singachea** [comment]
@josevalim :+1: 

But how do I **count(*)**? 

From https://github.com/elixir-lang/ecto/blob/4e3269d662d39f766fe866489081162f4b73bebf/lib/ecto/repo.ex#L159

```elixir
def aggregate(queryable, aggregate, field, opts \\ [])
    when aggregate in [:count, :avg, :max, :min, :sum] and is_atom(field) do
  Ecto.Repo.Queryable.aggregate(__MODULE__, @adapter, queryable, aggregate, field, opts)
end
``` 

The `field` need to be an atom this case.
