### ISSUE TITLE
mix ecto.create works, mix ecto.migrate doesn't, on MySQL

### ISSUE THREAD

**Issue by amencarini** [elixir-lang/ecto#1310]
### Environment

* Elixir version: 1.2.1
* Database and version: MySQL 5.7.10
* Ecto version: 1.1.4
* Database adapter and version: mariaex 0.7.0
* Operating system: OS X 10.11.3

### Current behavior

```
$ mix ecto.create
The database for MysqlIssue.Repo has been created.
$ mix ecto.migrate

12:27:10.163 [error] Mariaex.Protocol (#PID<0.182.0>) failed to connect: ** (Mariaex.Error) tcp connect: econnrefused
** (DBConnection.Error) connection not available
    (db_connection) lib/db_connection.ex:817: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:717: DBConnection.run/3
    (db_connection) lib/db_connection.ex:957: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:421: DBConnection.query/4
    (mariaex) lib/mariaex.ex:138: Mariaex.query/4
    (ecto) lib/ecto/adapters/mysql/connection.ex:25: Ecto.Adapters.MySQL.Connection.query/4
    (ecto) lib/ecto/adapters/sql.ex:259: Ecto.Adapters.SQL.query/7
    (ecto) lib/ecto/pool.ex:159: Ecto.Pool.do_run/4
    (ecto) lib/ecto/adapters/sql.ex:247: Ecto.Adapters.SQL.query/6
    (ecto) lib/ecto/adapters/sql.ex:225: Ecto.Adapters.SQL.query/5
    (ecto) lib/ecto/adapters/sql.ex:183: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/mysql.ex:85: anonymous fn/4 in Ecto.Adapters.MySQL.execute_ddl/3
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/mysql.ex:85: Ecto.Adapters.MySQL.execute_ddl/3
    (ecto) lib/ecto/migrator.ex:43: Ecto.Migrator.migrated_versions/2
    (ecto) lib/ecto/migrator.ex:142: Ecto.Migrator.run/4
    (ecto) lib/mix/tasks/ecto.migrate.ex:63: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```
### Expected behavior

`mix ecto.migrate` should run the expected migration (in this case, a new table should be created.)

**Comment by josevalim** [comment]
@amencarini that's because creating uses mysql from the command line while migrate uses the tcp socket. Can you please check your repository options in your config files? Does it have the proper host and port? Does `ping localhost` work on your terminal?

**Comment by amencarini** [comment]
Yup, config issue on my side, got confused by the fact that the former command worked. Thanks!
