### ISSUE TITLE
Repo.preload doesn't work when "through" objects are preloaded

### ISSUE THREAD

**Issue by halldors** [elixir-lang/ecto#1311]
### Environment

* Elixir version (elixir -v): Elixir 1.2.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): mysql 5.6 (google hosted sql instance)
* Ecto version (mix deps): {:phoenix_ecto, "~> 2.0"} 
* Database adapter and version (mix deps): {:mariaex, "~> 0.7"},
* Operating system: OS X 10.11.3 Mac

### Current behavior

I'm trying to preload the users after I insert a new team with members, for rendering the json.

I have this schemas

```
# teams model 
  schema "teams" do
    field :name, :string
    has_many :members, Foosball.Member
    has_many :users, through: [:members, :user]
    timestamps
  end

  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> cast_assoc(:members)
  end

  # members model
  schema "members" do
    belongs_to :team, Foosball.Team
    belongs_to :user, Foosball.User

    timestamps
  end

  # team controller
def create(conn, %{"team" => team_params}) do
    team = Team.changeset(%Team{}, team_params)
    case Repo.insert(team) do
      {:ok, team} ->
        IO.inspect team
#        team = Repo.get!(Team, team.id)
        team = Repo.preload(team, :users)
        IO.inspect team
        conn
        |> put_status(:created)
        |> put_resp_header("location", team_path(conn, :show, team))
        |> render("show.json", team: team)
      {:error, changeset} ->
...

````
users are not preloaded into team. I get this error.
```
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function Ecto.Association.NotLoaded.__schema__/1
        (ecto) Ecto.Association.NotLoaded.__schema__(:primary_key)
        (ecto) lib/ecto.ex:412: Ecto.primary_key/1
        (ecto) lib/ecto.ex:425: Ecto.primary_key!/1
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
        (foosball) web/controllers/team_controller.ex:25: Foosball.TeamController.create/2
        (foosball) web/controllers/team_controller.ex:1: Foosball.TeamController.action/2
        (foosball) web/controllers/team_controller.ex:1: Foosball.TeamController.phoenix_controller_pipeline/2
        (foosball) lib/phoenix/router.ex:261: Foosball.Router.dispatch/2
        (foosball) web/router.ex:1: Foosball.Router.do_call/2
        (foosball) lib/foosball/endpoint.ex:1: Foosball.Endpoint.phoenix_pipeline/1
```

Here is the printout of the team obj. before preloading
```
%Foosball.Team{__meta__: #Ecto.Schema.Metadata<:loaded>, id: 27,
 inserted_at: #Ecto.DateTime<2016-03-12T17:12:09Z>,
 members: [%Foosball.Member{__meta__: #Ecto.Schema.Metadata<:loaded>, id: 45,
   inserted_at: #Ecto.DateTime<2016-03-12T17:12:09Z>,
   team: #Ecto.Association.NotLoaded<association :team is not loaded>,
   team_id: 27, updated_at: #Ecto.DateTime<2016-03-12T17:12:09Z>,
   user: #Ecto.Association.NotLoaded<association :user is not loaded>,
   user_id: 1},
  %Foosball.Member{__meta__: #Ecto.Schema.Metadata<:loaded>, id: 46,
   inserted_at: #Ecto.DateTime<2016-03-12T17:12:10Z>,
   team: #Ecto.Association.NotLoaded<association :team is not loaded>,
   team_id: 27, updated_at: #Ecto.DateTime<2016-03-12T17:12:10Z>,
   user: #Ecto.Association.NotLoaded<association :user is not loaded>,
   user_id: 2}], name: "Noobs",
 updated_at: #Ecto.DateTime<2016-03-12T17:12:09Z>,
 users: #Ecto.Association.NotLoaded<association :users is not loaded>}
```

However if I refetch the team again (uncomment the Repo.get!..) It works. 
 
### Expected behavior

I expect the the users to become preloaded after the Repo.preload call.

**Comment by josevalim** [comment]
This is fixed in Ecto master where we support a :force option. Thank you!
