### ISSUE TITLE
Ecto.assoc -> through -> through (again)

### ISSUE THREAD

**Issue by parkerl** [elixir-lang/ecto#1312]
* Elixir version (elixir -v): Elixir 1.2.0
* PostgreSQL 9.4
```
connection 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (connection)
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy)
  ok
* decimal 1.1.1 (Hex package) (mix)
  locked at 1.1.1 (decimal)
  ok
* poison 1.5.2 (Hex package) (mix)
  locked at 1.5.2 (poison)
  ok
* sbroker 0.7.0 (Hex package) (rebar)
  locked at 0.7.0 (sbroker)
  ok
* db_connection 0.2.4 (Hex package) (mix)
  locked at 0.2.4 (db_connection)
  ok
* postgrex 0.11.1 (Hex package) (mix)
  locked at 0.11.1 (postgrex)
  ok
* mariaex 0.7.0 (Hex package) (mix)
  locked at 0.7.0 (mariaex)
  ok
```
* Operating system: OSX

I think there is still an issue with `Ecto.assoc` related to #1299.

I have an example here (I hope it isn't just setup): https://github.com/parkerl/ecto/commit/2ec120090f43f49456b44ca2d5569d304521f83e
`assert [^e2, ^e1] = TestRepo.all(query)` gives:

```
** (ArgumentError) argument error
     stacktrace:
       (ecto) lib/ecto/adapters/postgres/connection.ex:388: Ecto.Adapters.Postgres.Connection.expr/3
       (ecto) lib/ecto/adapters/postgres/connection.ex:464: Ecto.Adapters.Postgres.Connection.expr/3
       (ecto) lib/ecto/adapters/postgres/connection.ex:301: anonymous fn/3 in Ecto.Adapters.Postgres.Connection.join/2
       (elixir) lib/enum.ex:1120: anonymous fn/4 in Enum.map_join/3
       (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1118: Enum.map_join/3
       (ecto) lib/ecto/adapters/postgres/connection.ex:108: Ecto.Adapters.Postgres.Connection.all/1
       (ecto) lib/ecto/adapters/postgres.ex:56: Ecto.Adapters.Postgres.prepare/2
       (ecto) lib/ecto/query/planner.ex:99: Ecto.Query.Planner.query_without_cache/3
       (ecto) lib/ecto/query/planner.ex:40: Ecto.Query.Planner.query/4
       (ecto) lib/ecto/repo/queryable.ex:119: Ecto.Repo.Queryable.execute/5
       (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
       integration_test/cases/assoc.exs:111
```

I have been trying in vain to figure out the issue.

The error raised at `connection.ex:388` seems to be because the join indexes get mixed up. You can see in `lib.ecto.association.ex:584` that the joins after these calls look like this:

```
    query =
      %{query | joins: query.joins ++ [join]}
      |> joins_query(t, position)
      |> Ecto.Query.Planner.prepare_sources(:adapter_wont_be_needed)

[%Ecto.Query.JoinExpr{assoc: nil,
  file: "...ecto/lib/ecto/association.ex",
  ix: 1, line: 392,
  on: %Ecto.Query.QueryExpr{expr: {:in, [],
    [{{:., [], [{:&, [], [1]}, :post_id]}, [], []}, {:^, [], [0]}]},
   file: "...ecto/lib/ecto/association.ex",
   line: 392, params: [{[213], {:in_spread, {1, :post_id}}}]}, params: %{},
  qual: :inner, source: {"comments", Ecto.Integration.Comment}},
 %Ecto.Query.JoinExpr{assoc: nil,
  file: "...ecto/lib/ecto/association.ex",
  ix: 3, line: 385,
  on: %Ecto.Query.QueryExpr{expr: {:==, [],
    [{{:., [], [{:&, [], [3]}, :comment_id]}, [], []},
     {{:., [], [{:&, [], [1]}, :id]}, [], []}]},
   file: "...ecto/lib/ecto/association.ex",
   line: 385, params: []}, params: [], qual: :inner,
  source: {"comments_emojis", Ecto.Integration.CommentEmoji}},
 %Ecto.Query.JoinExpr{assoc: nil,
  file: "...ecto/lib/ecto/association.ex",
  ix: 2, line: 716,
  on: %Ecto.Query.QueryExpr{expr: {:==, [],
    [{{:., [], [{:&, [], [2]}, :id]}, [], []},
     {{:., [], [{:&, [], [3]}, :emoji_id]}, [], []}]},
   file: "...ecto/lib/ecto/association.ex",
   line: 716, params: []}, params: [], qual: :inner,
  source: {"emojis", Ecto.Integration.Emoji}}]
```

Notice that `ix` goes 1,3,2. There are only 3 sources in this query so the call to `elem` at `connection.ex:388` is out of range.

It seems that this happens because `joins_query` is called, and then called again inside `Ecto.Query.Planner.prepare_sources`. 

I have taken a couple stabs at fixes but this is beyond me. Sorry. :confused:

**Comment by josevalim** [comment]
@parkerl could you please provide a test case that uses our existing features? I would love to use your test but we already have too many fixtures. :D

**Comment by josevalim** [comment]
Also can you please check if this has been fixed in master? Thank you!

**Comment by parkerl** [comment]
Yes and yes.

**Comment by parkerl** [comment]
@josevalim it seems to still be an issue. The issue appears with the test here https://github.com/parkerl/ecto/commit/7313596a85453cf163c9d87f459192ae112dc6b3.

Please let me know if I can further help with this one.

**Comment by josevalim** [comment]
Thank you for the mechanism to reproduce this, indeed, it was not an easy one :) Fixed on master! 
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by parkerl** [comment]
Thanks @josevalim
