### ISSUE TITLE
Cannot create index on timestamp if it has been renamed (Ecto 2.0)

### ISSUE THREAD

**Issue by sikanhe** [elixir-lang/ecto#1349]
```
    create table(:posts) do
      add :title, :string
      add :slug,  :string

      timestamps inserted_at: :created_at
    end

    create index(:posts, [:created_at])
```

throws 
```
17:05:42.362 [error] GenServer #PID<0.225.0> terminating
** (Postgrex.Error) ERROR (undefined_column): column "created_at" does not exist
    (ecto) lib/ecto/adapters/sql.ex:180: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:56: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:56: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:90: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:88: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
```

**Comment by josevalim** [comment]
The `timestamps` function in migrations do not accept column names like that:

https://github.com/elixir-lang/ecto/blob/master/lib/ecto/migration.ex

 If you would like to provide this feature, then please send a PR. Otherwise, the error is expected. :)

**Comment by sikanhe** [comment]
https://github.com/elixir-lang/ecto/pull/1350
