### ISSUE TITLE
MariaEx DateTime incompatibility

### ISSUE THREAD

**Issue by migore** [elixir-lang/ecto#1397]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 18 [erts-7.3] [source] [64-bit]
Elixir 1.2.3

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
MySQL 5.6.10-log
* Ecto version (mix deps):
  ecto: 1.1.4

* Database adapter and version (mix deps):
  mariaex: 0.7.4
* Operating system:
Mac OS 10.11.4

### Current behavior

I'm trying to query the database (without Ecto DSL) filtering by datetime with the following code:

```elixir
current_datetime = Ecto.DateTime.utc
Ecto.Adapters.SQL.query(CheckinService.ReadRepo, "select * from Users where userLastLogin < ?", [current_datetime])
```

However, I get the following error:
```
  ** (exit) an exception was raised:
      ** (ArgumentError) query has invalid parameter #Ecto.DateTime<2016-04-25T21:55:53Z>
          (mariaex) lib/mariaex/query.ex:127: DBConnection.Query.Mariaex.Query.encode_param/1
          (mariaex) lib/mariaex/query.ex:79: DBConnection.Query.Mariaex.Query.encode_params/2
          (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
          (mariaex) lib/mariaex/query.ex:74: DBConnection.Query.Mariaex.Query.parameters_to_binary/1
          (db_connection) lib/db_connection.ex:885: DBConnection.describe_execute/5
          (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
          (db_connection) lib/db_connection.ex:957: DBConnection.run_meter/3
          (db_connection) lib/db_connection.ex:421: DBConnection.query/4
          (mariaex) lib/mariaex.ex:138: Mariaex.query/4
          (ecto) lib/ecto/adapters/mysql/connection.ex:25: Ecto.Adapters.MySQL.Connection.query/4
          (stdlib) timer.erl:197: :timer.tc/3
          (ecto) lib/ecto/adapters/sql.ex:262: Ecto.Adapters.SQL.query/7
          (ecto) lib/ecto/pool.ex:159: Ecto.Pool.do_run/4
          (ecto) lib/ecto/adapters/sql.ex:247: Ecto.Adapters.SQL.query/6
          (ecto) lib/ecto/adapters/sql.ex:225: Ecto.Adapters.SQL.query/5
          (checkin_service) web/controllers/checkin_controller.ex:9: CheckinService.CheckinController.index/2
          (checkin_service) web/controllers/checkin_controller.ex:1: CheckinService.CheckinController.action/2
          (checkin_service) web/controllers/checkin_controller.ex:1: CheckinService.CheckinController.phoenix_controller_pipeline/2
          (checkin_service) lib/phoenix/router.ex:261: CheckinService.Router.dispatch/2
          (checkin_service) web/router.ex:1: CheckinService.Router.do_call/2
```

### Expected behavior

As a Elixir/Phoenix noob I thought it would receive a DateTime and handle converting to mariaex/Mysql format.

### Workaround

I checked Mariaex tests and it uses the format ```{{2016, 4, 25}, {10, 10, 30, 0}}```. [source](https://github.com/xerions/mariaex/blob/master/test/query_test.exs#L263)

My first attempt was to try to use ```Ecto.DateTime.to_erl```, but the output was missing the milliseconds:
```elixir
iex> Ecto.DateTime.utc() |> Ecto.DateTime.to_erl
# {{2016, 4, 25}, {22, 3, 23}}
```

And I got a similar error:
```
** (exit) an exception was raised:
    ** (ArgumentError) query has invalid parameter {{2016, 4, 25}, {17, 26, 24}}
```

My fix for now is to manually add the milliseconds to this tuple:
```elixir
{ date, time } = CheckinService.Checkin.now_in_central_time() |> Ecto.DateTime.to_erl
mariaex_time = Tuple.append(time, 0)
current_datetime = { date, mariaex_time }                                                                                                                                                                                          
Ecto.Adapters.SQL.query(CheckinService.ReadRepo, "select * from Users where userLastLogin < ?", [current_datetime])
```

I'm not sure if this issue belongs here or in mariaex, but I guess it's here. Apologies if I'm mistaken.

**Comment by josevalim** [comment]
Yes, this is a limitation of how Ecto 1.0 works but it is fixed in Ecto 2.0 which is in RC stage and it will be shipped soon. :) Thank you!
