### ISSUE TITLE
Can't run migrations on two repos if app is already started

### ISSUE THREAD

**Issue by paulcsmith** [elixir-lang/ecto#1413]
### Environment

* Elixir version (elixir -v): 1.2.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 9.4.5
* Ecto version (mix deps): 2.0 rc4
* Database adapter and version (mix deps): postgrex
* Operating system: OS X

### Current behavior

This mix task fails if there are there are 2 or more repos, and the app is started

```elixir
# This is the bare minimum case where this fails
defmodule Mix.Tasks.MyApp.Migrate do
  use Mix.Task

  def run(_opts) do
    Mix.Task.run "app.start"
    Mix.Tasks.Ecto.Migrate.run([])
  end
end
```

The failure message is:

```
** (ArgumentError) argument error
    (stdlib) :ets.lookup(225341, 20)
    (postgrex) lib/postgrex/types.ex:294: Postgrex.Types.fetch!/2
    (postgrex) lib/postgrex/types.ex:222: Postgrex.Types.decoder/2
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (postgrex) lib/postgrex/query.ex:91: DBConnection.Query.Postgrex.Query.decoders/2
    (postgrex) lib/postgrex/query.ex:44: DBConnection.Query.Postgrex.Query.describe/2
    (db_connection) lib/db_connection.ex:884: DBConnection.describe_execute/5
    (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:957: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:535: DBConnection.prepare_execute/4
    (ecto) lib/ecto/adapters/sql.ex:390: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:127: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
    (ecto) lib/ecto/migrator.ex:142: Ecto.Migrator.run/4
    (ecto) lib/mix/tasks/ecto.migrate.ex:70: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (my_app) lib/mix/tasks/migrate.ex:13: Mix.Tasks.MyApp.Migrate.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

### Expected behavior

Pre Ecto 2.0 you could start the app and run migrations. In Ecto 2.0, if you start the app and run migrations for a single repo it work. If you run migrations and have 2 repos, the first repo is migrated, but the second returns the error above. The fix is simple, just remove `Mix.Task.run "app.start"`, but this was not very clear from the error message

A helpful error message, or adding something to an upgrade guide would be wonderful :D

**Comment by josevalim** [comment]
Thanks, I will make sure to include it in the update guide.

**Comment by paulcsmith** [comment]
Thanks, José!
