### ISSUE TITLE
Query with UUID

### ISSUE THREAD

**Issue by boriscy** [elixir-lang/ecto#1424]
I can't query with uuid, I have this function on my model
```elixir
def users do
  Repo.all(
    from u in User,
    where: u.id == "93fd15fb-fe21-4a59-813d-f80447417a23",
    select: u
  )
end
```
and I get this error
```
** (Postgrex.Error) ERROR (character_not_in_repertoire): invalid byte sequence for encoding "UTF8": 0x93
[debug] QUERY ERROR db=8.2ms queue=0.2ms
SELECT u0."id", u0."full_name", u0."email", u0."encrypted_password", u0."settings", u0."organizations", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."id" = '��^U��!JY�=�^DGAz#') []
    (ecto) lib/ecto/adapters/sql.ex:395: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:127: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
```
I have read this issue (https://github.com/elixir-lang/ecto/issues/1405) and I knew that I can use Ecto.UUID.dump

### Environment

* Elixir 1.2.5
* PostgreSQL 9.5:
* Ecto 2.0.0-rc.4:
* Linux Mint 17.1:

**Comment by josevalim** [comment]
I will investigate it. For now, it should probably work if you interpolate it: ^"9dac321-..."

**Comment by boriscy** [comment]
It did not work with interpolation ^"9dac3,..."
```
** (CompileError) iex:14: cannot use ^"93fd15fb-fe21-4a59-813d-f80447417a23" outside of match clauses
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
```

**Comment by josevalim** [comment]
@boriscy please `import Ecto.Query` before building the query. :)

**Comment by boriscy** [comment]
Yeah that fixed, have asked this on stackoverflow before posting here and didn't got an answer, thanks a lot sorry for not being careful and wasting your time
