### ISSUE TITLE
Unable to encode value `[desc: "created_at", asc: "updated_at"]` as type text

### ISSUE THREAD

**Issue by jeregrine** [elixir-lang/ecto#348]
I have this code
```elixir
query = (from u in User, order_by: ^params["sort"])                                                                      
users = Repo.all(query)             
```

And I get that error, full trace:
```elixir
Request: GET /api/users?sort=-created_at,updated_at
** (exit) an exception was raised:
    ** (Postgrex.Error) unable to encode value `[desc: "created_at", asc: "updated_at"]` as type text
        (ecto) lib/ecto/adapters/postgres/worker.ex:18: Ecto.Adapters.Postgres.Worker.query!/4
        (ecto) lib/ecto/adapters/postgres.ex:270: Ecto.Adapters.Postgres.use_worker/3
        (stdlib) timer.erl:165: :timer.tc/1
        (comet_api) lib/repo.ex:2: Repo.log/2
        (ecto) lib/ecto/adapters/postgres.ex:64: Ecto.Adapters.Postgres.all/4
        (ecto) lib/ecto/repo/queryable.ex:20: Ecto.Repo.Queryable.all/4
        (comet_api) web/controllers/user_controller.ex:14: CometApi.UserController.index/2
        (comet_api) web/controllers/user_controller.ex:1: CometApi.UserController.phoenix_controller_pipeline/2
```

I have a hunch of whats causing it, but wanted to make this before I fell a sleep.

**Comment by josevalim** [comment]
You need to traverse the params and build the query. Something like:

```elixir
Enum.reduce String.split(params["sort], ","), query, fn
  "-" <> field, query -> order_by(query, [q], desc: field(q, ^String.to_existing_atom(field))
  field, query -> order_by(query, [q], field(q, ^String.to_existing_atom(field))
end
```

We can always make this easier, but I am sure it would require you to at least make the values atoms too.

**Comment by jeregrine** [comment]
ahh I guess I missed the `u.field` what is the [q] parameter.

Hm. this is kind of gross, but it makes sense.

**Comment by jeregrine** [comment]
basically I was traversing the params and I was passing in `[desc: "created_at", asc: "updated_at"]` I just need to find a way to make it p.created_at without passing my query and its table alias all over the place :-/.

Right now I have  "clean_params" method which casts all my params, filters out params I don't support etc and then I basically pass it into the query.

**Comment by josevalim** [comment]
I will work on this feature tomorrow.

**Comment by jeregrine** [comment]
<3

**Comment by josevalim** [comment]
Pushed to master.

**Comment by jeregrine** [comment]
💖💖💖💖
