### ISSUE TITLE
Preload with UUID primary keys not working anymore

### ISSUE THREAD

**Issue by briksoftware** [elixir-lang/ecto#455]
All my models use UUIDs for the id field. Simple SELECT queries work, but preloading stopped working:

```** (Protocol.UndefinedError) protocol Enumerable not implemented for %Ecto.Query.Tagged{tag: nil, type: {:array, :uuid}, value: [<<56, 103, 5, 15, 1, 208, 65, 148, 150, 123, 86, 146, 51, 48, 205, 218>>]}
     stacktrace:
       (ecto) lib/ecto/query/planner.ex:84: Ecto.Query.Planner.prepare/2
       (ecto) lib/ecto/query/planner.ex:63: Ecto.Query.Planner.query/3
       (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/4
       (ecto) lib/ecto/repo/preloader.ex:66: anonymous fn/3 in Ecto.Repo.Preloader.do_preload/3
       (elixir) lib/enum.ex:977: Enum."-map/2-lc$^0/1-0-"/2
       (ecto) lib/ecto/repo/preloader.ex:57: Ecto.Repo.Preloader.do_preload/3
       (ecto) lib/ecto/repo/preloader.ex:19: Ecto.Repo.Preloader.query/4
       (ecto) lib/ecto/repo/queryable.ex:43: Ecto.Repo.Queryable.one/4```

**Comment by josevalim** [comment]
Fixed in master. Please give it a try and if everything is good I will release 0.8.1 afterwards.

**Comment by briksoftware** [comment]
it's fixed. Thanks!

**Comment by josevalim** [comment]
v0.8.1 is out!
