### ISSUE TITLE
mix ecto.migrate fails

### ISSUE THREAD

**Issue by optikfluffel** [elixir-lang/ecto#497]
Hi,

when using your [simple example](https://github.com/elixir-lang/ecto/tree/master/examples/simple) and modifying [`mix.exs#L15-L18`](https://github.com/elixir-lang/ecto/blob/master/examples/simple/mix.exs#L15-L18) to use current versions:

```elixir
defp deps do
  [{:postgrex, "~> 0.8.0"},
   {:ecto, "~> 0.8.1"}]
end
```

the `mix ecto.migrate` command fails with:

```
13:10:37.919 [info]  == Running Repo.CreatePosts.up/0 forward

13:10:37.919 [info]  create table weather

13:10:37.928 [info]  == Migrated in 0.0s
** (FunctionClauseError) no function clause matching in Postgrex.Extensions.Binary.encode_timestamp/1
    (postgrex) lib/postgrex/extensions/binary.ex:203: Postgrex.Extensions.Binary.encode_timestamp({{2015, 3, 3}, {12, 10, 37}})
    (postgrex) lib/postgrex/protocol.ex:280: anonymous fn/2 in Postgrex.Protocol.encode_params/1
    (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:977: Enum.map/2
    (postgrex) lib/postgrex/protocol.ex:275: Postgrex.Protocol.encode_params/1
    (postgrex) lib/postgrex/protocol.ex:245: Postgrex.Protocol.send_params/2
    (postgrex) lib/postgrex/protocol.ex:126: Postgrex.Protocol.message/3
```

Thanks

**Comment by josevalim** [comment]
Please add {:postgrex, "~> 0.7.0"} for now to your dependencies. You are using ecto with an incompatible version of postgrex (likely 0.8.0). :)
