### ISSUE TITLE
Ecto.Repo.one ignores the "where" from an Ecto.Query

### ISSUE THREAD

**Issue by jeznet** [elixir-lang/ecto#573]
For a test case like this:
```
defmodule MyApp.CommentTest do
  use ExUnit.Case, async: false

  test "insert, get" do
    comment = %MyApp.Comment{
      web_content_id: 10,
      content: "test",
      published_at: {{2015, 04, 28}, {08, 25, 58, 0}},
    }
    assert %MyApp.Comment{} = Repo.insert(comment)

    comment = %MyApp.Comment{
      web_content_id: 11,
      content: "some test",
      published_at: {{2015, 04, 28}, {08, 25, 59, 0}},
    }
    assert %MyApp.Comment{} = Repo.insert(comment)

    q = from c in MyApp.Comment,
      where: c.content == "test"
    comment = Repo.one!(q)
    assert %MyApp.Comment{ web_content_id: 10 } = comment
  end
end
```
running `mix test` gives:
```
  1) test insert, get, update, delete (Ehnix.CommentTest)
     test/my_app/models/comment_test.exs:6
     ** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:
     
     from c in Ehnix.Comment
     
     stacktrace:
       (ecto) lib/ecto/repo/queryable.ex:46: Ecto.Repo.Queryable.one/4
       test/ehnix/models/comment2_test.exs:28
```
The where clause seems to disappear...

After changing the query to:
```
    q = from c in MyApp.Comment,
      where: c.content == "not  existing text
```
it gets:
```
     ** (Ecto.NoResultsError) expected at least one result but got none in query:
     
     from c in Ehnix.Comment,
       where: c.content == "non existing text"
```
so the where part appears.

Strangely this code works for me in IEx.

Versions:
```
$ cat mix.lock | grep ecto
  "ecto": {:hex, :ecto, "0.10.2"},
$ elixir -v
Elixir 1.0.4
$ psql --version
psql (PostgreSQL) 9.3.6
```

**Comment by josevalim** [comment]
Can you provide a way to reproduce this in Ecto repo? Or a failing test in Ecto's sample application in the examples directory? I have tried it and everything just works™.

**Comment by jeznet** [comment]
Issue resolved. I had overlooked something and posted only a part of my code to the example above. Some code down the line which was using Repo.one(Comment) not Repo.one(q) was causing the error message (of course then without the where clause) and confused me.
Sorry for posting an incomplete example and bothering you.

Here is the output:
```
$ mix test                                                                                                                                                                       
..
$ mix test

  1) test insert, get (MyApp.CommentTest)
     test/ehnix/models/comment2_test.exs:6
     ** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:
     
     from c in Comment
     
     stacktrace:
       (ecto) lib/ecto/repo/queryable.ex:46: Ecto.Repo.Queryable.one/4
       test/ehnix/models/comment_test.exs:29  # => code with Repo.one(Comment)

# Second run from the example above:

  1) test insert, get (MyApp.CommentTest)
     test/ehnix/models/comment_test.exs:6
     ** (Ecto.NoResultsError) expected at least one result but got none in query:
     
     from c in Comment,
       where: c.content == "non existing text"
     
     stacktrace:
       (ecto) lib/ecto/repo/queryable.ex:56: Ecto.Repo.Queryable.one!/4
       test/ehnix/models/comment_test.exs:23 # different line (not 29)
```

Anyway maybe that could be a good idea to write somewhere in the docu that `Repo.one(Comment)` expands to:Repo.one(from c in Comment)`, or is it already somewhere?

**Comment by ericmj** [comment]
`Repo.one` is specced to take a `Queryable`, both `from ...` and models implement that protocol.
