### ISSUE TITLE
If begin raises in a nested transaction the outer transaction is rolledback to an invalid or previous savepoint at the same level

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/ecto#611]
Using the `Simple` example and a raw query that raises because `bad` is not a column:
```elixir
defmodule SimpleTransaction do
  def test do
    Simple.Repo.transaction(fn ->
      try do
        Ecto.Adapters.SQL.query(Simple.Repo, "UPDATE weather SET bad = bad + 1", [])
      catch
        _, _ ->
          :ok
      end
      Simple.Repo.transaction(fn -> :ok end)
      :ok
    end)
  end
end
```
Results in the following exception when a transaction is attempted:
```
** (Postgrex.Error) ERROR (invalid_savepoint_specification): no such savepoint
      (ecto) lib/ecto/adapters/sql/worker.ex:60: Ecto.Adapters.SQL.Worker.call!/3
    (simple) lib/simple.ex:13: Simple.Repo.log/2
      (ecto) lib/ecto/adapters/sql.ex:451: Ecto.Adapters.SQL.transaction/3
             lib/simple.ex:50: anonymous fn/0 in SimpleTransaction.test/0
      (ecto) lib/ecto/adapters/sql.ex:442: Ecto.Adapters.SQL.transaction/3
```
Or when a previous transaction has occurred at the same level:
```elixir
defmodule SimpleTransaction do
  def test do
    Simple.Repo.transaction(fn ->
      Simple.Repo.transaction(fn -> :ok end)
      try do
        Ecto.Adapters.SQL.query(Simple.Repo, "UPDATE weather SET bad = bad + 1", [])
      catch
        _, _ ->
          :ok
      end
      Simple.Repo.transaction(fn -> :ok end)
      :ok
    end)
  end
end
```
The begin raises but the rollback succeeds and rolls back to the beginning of the prior transaction at the same level:
```
** (Postgrex.Error) ERROR (in_failed_sql_transaction): current transaction is aborted, commands ignored until end of transaction block
      (ecto) lib/ecto/adapters/sql/worker.ex:60: Ecto.Adapters.SQL.Worker.call!/3
    (simple) lib/simple.ex:13: Simple.Repo.log/2
      (ecto) lib/ecto/adapters/sql.ex:441: Ecto.Adapters.SQL.transaction/3
             lib/simple.ex:51: anonymous fn/0 in SimpleTransaction.test/0
      (ecto) lib/ecto/adapters/sql.ex:442: Ecto.Adapters.SQL.transaction/3
```

This can combine with #610 for utter confusion:
```elixir
defmodule SimpleTransaction do
  def test do
    Simple.Repo.transaction(fn ->
        Simple.Repo.transaction(fn ->
          try do
            Ecto.Adapters.SQL.query(Simple.Repo, "UPDATE weather SET bad = bad + 1", [])
          catch
            _, _ ->
              :ok
          end
        end)
        try do
          Simple.Repo.insert(%Weather{city: "London", prcp: nil})
        catch
          _,_ ->
            :ok
        end
        Simple.Repo.insert(%Weather{city: "Paris", prcp: nil})
    end)
  end
end
```
No error is raised and only Paris is inserted.

**Comment by josevalim** [comment]
We have agreed that if begin/rollback/savepoint command fails, we will always assume the connection has gone bad because it is impossible to know the reason the command fail without checking case by case or going adapter specific.
