### ISSUE TITLE
UUID not being auto generated

### ISSUE THREAD

**Issue by fbjork** [elixir-lang/ecto#709]
I'm using the ecto from the latest master and I'm trying to get UUIDs to auto generate before being inserted to Postgres, but I don't see the id being inserted.

Here's my model, am I missing something or is this a bug?

```elixir
defmodule FeedService.Feed do
  use FeedService.Web, :model

  schema "feeds" do
    field :user_id, :string
    field :name, :string
    field :filters, :map
    timestamps
  end

  @primary_key {:id, :binary_id, autogenerate: true}
  @required_fields ~w(user_id name)
  @optional_fields ~w(filters)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If `params` are nil, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

```

```
[info] POST /feeds
[info] Processing by FeedService.FeedController.create/2
  Parameters: %{"feed" => %{"filters" => %{"foo_id" => ["324"], "bar_id" => ["152"]}, "name" => "Test", "user_id" => "1723423"}, "format" => "json"}
  Pipelines: [:api]
[debug] BEGIN [] OK query=0.3ms
[debug] INSERT INTO "feeds" ("filters", "inserted_at", "name", "updated_at", "user_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id" [%{"foo_id" => ["324"], "bar_id" => ["152"]}, {{2015, 6, 26}, {17, 50, 11, 0}}, "Test", {{2015, 6, 26}, {17, 50, 11, 0}}, "1723423"] ERROR query=0.4ms
[debug] ROLLBACK [] OK query=0.2ms
[info] Sent 500 in 21ms
[error] #PID<0.975.0> running FeedService.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /feeds
** (exit) an exception was raised:
    ** (Postgrex.Error) ERROR (not_null_violation): null value in column "id" violates not-null constraint
        (ecto) lib/ecto/adapters/sql.ex:184: Ecto.Adapters.SQL.query/4
        (ecto) lib/ecto/adapters/sql.ex:475: Ecto.Adapters.SQL.model/5
        (ecto) lib/ecto/repo/model.ex:52: anonymous fn/10 in Ecto.Repo.Model.insert!/4
        (ecto) lib/ecto/adapters/sql.ex:548: Ecto.Adapters.SQL.transaction/8
        (ecto) lib/ecto/adapters/pool.ex:414: Ecto.Adapters.Pool.do_transaction/4
        (ecto) lib/ecto/adapters/pool.ex:400: Ecto.Adapters.Pool.transaction/5
        (ecto) lib/ecto/adapters/sql.ex:524: Ecto.Adapters.SQL.transaction/3
        (ecto) lib/ecto/repo/model.ex:233: Ecto.Repo.Model.with_transactions_if_callbacks/6
```

**Comment by josevalim** [comment]
You need to define @primary_key before your schema block. Elixir is lexical, so the order statements like import, alias, and attributes are defined often matter.

**Comment by fbjork** [comment]
Got it, thanks!
