### ISSUE TITLE
Multiple order_by's and one empty causes invalid SQL to be generated

### ISSUE THREAD

**Issue by jeregrine** [elixir-lang/ecto#765]
```elixir
query = from(t in User, order_by: [desc: t.email], limit: ^20, offset: ^0)
|> order_by([t], [])
```

Returns
```sh
[debug] SELECT t0."id", t0."name", t0."email", t0."created_at", t0."updated_at" FROM "users" AS t0  ORDER BY t0."email" DESC,  LIMIT $1 OFFSET $2 [20, 0] ERROR query=2.9ms
** (exit) an exception was raised:
   ** (Postgrex.Error) ERROR (syntax_error): syntax error at or near "LIMIT"
       (ecto) lib/ecto/adapters/sql.ex:170: Ecto.Adapters.SQL.query/4
       (ecto) lib/ecto/adapters/sql.ex:390: Ecto.Adapters.SQL.all/6
       (ecto) lib/ecto/repo/queryable.ex:21: Ecto.Repo.Queryable.all/4
```

Can see the error in the order_by
```sql
ORDER BY t0."email" DESC,  LIMIT $1 OFFSET $2
             ~~~~~~~~~~~^
```

This is definitely a bug in my code that generates the empty [] but its also a little surprising so I figured I should post it.

**Comment by jeregrine** [comment]
PLEASE NOTE the code as shown may be slightly wrong, as I cleaned it up from the existing code base with lots more going on.

**Comment by jeregrine** [comment]
@mitchellhenke provided another more clear example https://gist.github.com/mitchellhenke/49f806677dc78062486f

**Comment by jeregrine** [comment]
Thanks @josevalim 💗💖💕💜

**Comment by mitchellhenke** [comment]
❤️
