### ISSUE TITLE
Migration with reference can not be rolled back

### ISSUE THREAD

**Issue by ashneyderman** [elixir-lang/ecto#804]
Here is my migration

```
defmodule EctoPlay.Repo.Migrations.Meteo do
  use Ecto.Migration

  def change do
    create table(:report) do
      add :name,  :string
      add :month, :string, size: 7
      timestamps
    end
    
    create table(:weather) do
      add :city,    :string, size: 40
      add :temp_lo, :integer
      add :temp_hi, :integer
      add :prcp,    :float
      add :report_id, references(:report)
      timestamps
    end
  end

end
```

Here is the result of ecto.migrate

```
10:05:45 ecto_play(master) > mix ecto.migrate -all --repo EctoPlay.Repo 

10:06:41.284 [info]  == Running EctoPlay.Repo.Migrations.Meteo.change/0 forward

10:06:41.284 [info]  create table report

10:06:41.290 [info]  create table weather

10:06:41.297 [info]  == Migrated in 0.1s
```

And here is the error rolling it back

```
10:06:41 ecto_play(master) > mix ecto.rollback -v 20150709201340 --repo EctoPlay.Repo 

10:06:54.667 [info]  == Running EctoPlay.Repo.Migrations.Meteo.change/0 backward

10:06:54.667 [info]  drop table report
** (Postgrex.Error) ERROR (dependent_objects_still_exist): cannot drop table report because other objects depend on it
    (ecto) lib/ecto/adapters/sql.ex:170: Ecto.Adapters.SQL.query/4
    (ecto) lib/ecto/adapters/postgres.ex:61: Ecto.Adapters.Postgres.execute_ddl/3
    _build/dev/lib/ecto_play/priv/repo/migrations/20150709201340_meteo.exs:5: EctoPlay.Repo.Migrations.Meteo.change/0
    (stdlib) timer.erl:194: :timer.tc/3
    (ecto) lib/ecto/migration/runner.ex:22: Ecto.Migration.Runner.run/6
    (ecto) lib/ecto/migrator.ex:113: Ecto.Migrator.attempt/6
    (ecto) lib/ecto/migrator.ex:93: anonymous fn/4 in Ecto.Migrator.do_down/4
    (ecto) lib/ecto/adapters/sql.ex:479: Ecto.Adapters.SQL.transaction/9
```

**Comment by josevalim** [comment]
We need to reverse the commands on rollback. Anyone interested in tackling this one?

**Comment by gjaldon** [comment]
@josevalim I'd be happy to take this on! Haven't looked into this in detail yet but will make time for it later in my day.

**Comment by josevalim** [comment]
Please do!
