### ISSUE TITLE
get_by: ** (Postgrex.Error) ERROR (undefined_function): operator does not exist: json = unknown

### ISSUE THREAD

**Issue by arathunku** [elixir-lang/ecto#929]
Hello,

I'm playing around with ecto, postgresql and json and I've issue with using `get_by/2` where one of the keys is a map(jsonb) type.

Some details:

deps versions:
  - postgresql 9.4.4
  - ecto 1.0.1
  - poison 1.5.0

error:
```
  1) test creates new bullet (Bulleter.Api.BulletsControllerTest)
     test/controllers/api/bullets_controller_test.exs:18
     ** (Postgrex.Error) ERROR (undefined_function): operator does not exist: json = unknown
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:172: Ecto.Adapters.SQL.query!/5
       (ecto) lib/ecto/adapters/sql.ex:465: Ecto.Adapters.SQL.execute/6
       (ecto) lib/ecto/repo/queryable.ex:95: Ecto.Repo.Queryable.execute/5
       (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
       (ecto) lib/ecto/repo/queryable.ex:44: Ecto.Repo.Queryable.one/4
       test/controllers/api/bullets_controller_test.exs:22
```

code that's causing the problem:
```elixir
  @valid_attrs %{content: %{"x" => 1}, name: "some content", receiver: "username"}

  test "creates new bullet" do
    conn = post conn, bullets_path(conn, :create), bullet: @valid_attrs
    assert Repo.get_by(Bullet, @valid_attrs)
  end
```

when I omit json attribute: 
```elixir
    assert Repo.get_by(Bullet, Map.delete(@valid_attrs, :content))
```
it works without a problem.

full trace from dbg:

```
iex(1)> Dbg.trace(:send)
%{counts: %{nonode@nohost: 1}, errors: %{}}
iex(2)> Bulleter.Repo.get_by Bulleter.Bullet, %{content: %{"x"=>1}}

** (Dbg) unknown event:
    {:trace, #PID<0.205.0>, :send, {:code_call, #PID<0.205.0>, {:ensure_loaded, List.Chars.List}}, :code_server}

** (Dbg) unknown event:
    {:trace, #PID<0.205.0>, :send, {:code_call, #PID<0.205.0>, {:ensure_loaded, Bulleter.Repo}}, :code_server}

** (Dbg) unknown event:
    {:trace, #PID<0.205.0>, :send, {:code_call, #PID<0.205.0>, {:ensure_loaded, Ecto.Queryable.Atom}}, :code_server}
[debug] SELECT b0."id", b0."name", b0."content", b0."receiver", b0."inserted_at", b0."updated_at" FROM "bullets" AS b0 WHERE (b0."content" = $1) [%{"x" => 1}] ERROR query=0.5ms
** (Postgrex.Error) ERROR (undefined_function): operator does not exist: json = unknown

** (Dbg) unknown event:
    {:trace, #PID<0.205.0>, :send, {:code_call, #PID<0.205.0>, {:ensure_loaded, Ecto.Queryable.Ecto.Query}}, :code_server}

** (Dbg) #PID<0.205.0> sends to #PID<0.193.0>:
    {:"$gen_call", {#PID<0.205.0>, #Reference<0.0.4.900>}, {:checkout, #Reference<0.0.4.899>, true}}

** (Dbg) #PID<0.205.0> sends to #PID<0.204.0>:
    {:"$gen_call", {#PID<0.205.0>, #Reference<0.0.4.902>}, {:checkout, :run}}

** (Dbg) unknown event:
    {:trace, #PID<0.205.0>, :send, {:code_call, #PID<0.205.0>, {:ensure_loaded, Access.List}}, :code_server}
    (ecto) lib/ecto/adapters/sql.ex:172: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/sql.ex:465: Ecto.Adapters.SQL.execute/6
    (ecto) lib/ecto/repo/queryable.ex:95: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
    (ecto) lib/ecto/repo/queryable.ex:44: Ecto.Repo.Queryable.one/4

** (Dbg) #PID<0.205.0> sends to #PID<0.210.0>:
    {:"$gen_call", {#PID<0.205.0>, #Reference<0.0.4.903>}, {:query, "SELECT b0.\"id\", b0.\"name\", b0.\"content\", b0.\"receiver\", b0.\"inserted_at\", b0.\"updated_at\" FROM \"bullets\" AS b0 WHERE (b0.\"content\" = $1)", [%{"x" => 1}]}}
iex(2)> 
** (Dbg) unknown event:
    {:trace, #PID<0.205.0>, :send, {:"$gen_cast", {:checkin, #PID<0.204.0>}}, Bulleter.Repo.Pool}

** (Dbg) unknown event:
    {:trace, #PID<0.205.0>, :send, {:code_call, #PID<0.205.0>, {:ensure_loaded, Inspect.List}}, :code_server}

** (Dbg) unknown event:
    {:trace, #PID<0.205.0>, :send, {:code_call, #PID<0.205.0>, {:ensure_loaded, Inspect.Map}}, :code_server}

** (Dbg) unknown event:
    {:trace, #PID<0.205.0>, :send, {:code_call, #PID<0.205.0>, {:ensure_loaded, Inspect.BitString}}, :code_server}

** (Dbg) unknown event:
    {:trace, #PID<0.205.0>, :send, {:code_call, #PID<0.205.0>, {:ensure_loaded, Inspect.Integer}}, :code_server}

** (Dbg) unknown event:
    {:trace, #PID<0.205.0>, :send, {:notify, {:debug, #PID<0.27.0>, {Logger, ["SELECT b0.\"id\", b0.\"name\", b0.\"content\", b0.\"receiver\", b0.\"inserted_at\", b0.\"updated_at\" FROM \"bullets\" AS b0 WHERE (b0.\"content\" = $1)", 32, "[%{\"x\" => 1}]", 32, "ERROR", [32, "query", 61, '0.5', 109, 115], []], {{2015, 9, 5}, {22, 32, 35, 535}}, [pid: #PID<0.205.0>, module: Bulleter.Repo, function: "log/1", line: 2, ecto_conn_pid: #PID<0.210.0>]}}}, Logger}

```

I wanted to report that here and I'll try to create a PR with a fix if that isn't something too advanced (only few hours with elixir). It looks like it doesn't serialize the columns specified as (map)(json) in schema.

 I hope I've not missed any details needed to debug the problem.

**Comment by ericmj** [comment]
I think the column may be of type `json`, not `jsonb`. Postgres doesn't support equality on `json`, change the column to `jsonb`.

**Comment by josevalim** [comment]
It seems @ericmj is right. Can you confirm @arathunku?

**Comment by josevalim** [comment]
Closing until we get more info, thanks!

**Comment by arathunku** [comment]
Sorry for the late response! I can confirm that indeed it was an issue, sorry for trouble and thank y'all for help! :)
