### ISSUE TITLE
Postgrex failure on model with @primary_key {:id, :binary_id, autogenerate: true}

### ISSUE THREAD

**Issue by walkr** [elixir-lang/ecto#979]
Postgrex fails when inserting data with autogenerated primary_key.

#### Model

```elixir
defmodule MyApp.User do
  use MyApp.Web, :model

  @primary_key {:id, :binary_id, autogenerate: true}

  schema "users" do
    field :fullname, :string
    field :username, :string
    field :phone, :string
    field :password, :string
    field :image, :string

    timestamps
  end

  @required_fields ~w(username phone)
  @optional_fields ~w(fullname password image)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> validate_length(:username, min: 1)
    |> unique_constraint(:username)
    |> unique_constraint(:phone)
  end
end

```

#### Insert Error

```elixir
** (FunctionClauseError) no function clause matching in Postgrex.Extensions.Binary.encode/4
    (postgrex) lib/postgrex/extensions/binary.ex:59: Postgrex.Extensions.Binary.encode(%Postgrex.TypeInfo{array_elem: 0, base_type: 0, comp_elems: [], input: "int4in", oid: 23, output: "int4out", receive: "int4recv", send: "int4send", type: "int4"}, <<255, 205, 146, 114, 178, 128, 77, 235, 145, 97, 136, 88, 40, 100, 1, 27>>, 159794, {9, 4, 4})
    (postgrex) lib/postgrex/protocol.ex:299: anonymous fn/2 in Postgrex.Protocol.encode_params/1
      (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
      (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
      (elixir) lib/enum.ex:977: Enum.map/2
    (postgrex) lib/postgrex/protocol.ex:294: Postgrex.Protocol.encode_params/1
    (postgrex) lib/postgrex/protocol.ex:264: Postgrex.Protocol.send_params/2
    (postgrex) lib/postgrex/connection.ex:417: Postgrex.Connection.new_data/2
    (postgrex) lib/postgrex/connection.ex:292: Postgrex.Connection.handle_info/2
      (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
      (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
      (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3
```

**Comment by josevalim** [comment]
If you are using `:binary_id`, you need to declare your primary key as binary id in your migrations too. Otherwise Ecto will send a binary value to an integer column and it will fail.

**Comment by josevalim** [comment]
Also, please don't forget to include the Ecto and Posgrex versions, as asked in the Contributing.md instructions.

**Comment by walkr** [comment]
Got it. Thank you!
